### ISSUE TITLE
[Meta-Issue] Secure saving keys and passwords

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#22]
This issue is for discussion of the entire password and key security process.

- [x] [Password shouldn't shown as clear text](https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/19)
- [x] [Generate SALT at the build or install](https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/20)
- [x] [Use keytar for saving passwords](https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/21)
- [x] [Filter passwords from persistent data](https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/31)
- [ ] [Don't store the encryption key and passwords in the same place](https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/37)

**Comment by baruchiro** [comment]
Closing, the project moved to https://github.com/brafdlog/budget-tracking
